apiVersion: v1
kind: Pod
metadata:
  labels:
    app: echo-server
    service: {{ .Service }}
    username: {{ .Username }}
  name: test-{{ .Service | replace "_" "-" }}-{{ .Username | replace "_" "-" }}
  namespace: smc-os2-dev
spec:
  containers:
  - image: jmalloc/echo-server:0.2.0
    imagePullPolicy: IfNotPresent
    name: echo
    ports:
    - name: http
      containerPort: 8080
    resources:
      limits:
        cpu: 350m
        memory: 384Mi
      requests:
        cpu: 52m
        memory: 192Mi
  imagePullSecrets:
  - name: fiware-platform-docker-account