apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: pro-sftp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sftp
    fiware/component: smc-sftp
    fiware/layer: sftp
    fiware/tenant: multiTenant
    helm.sh/chart: sftp
    job-name: pro-{{ .Service }}-{{ .Username }}
  name: pro-sftp-setup-f4qtd
  namespace: smc-os2-pro
spec:
  containers:
  - args:
    - /etc/sftpgo/update.py
    - -u
    - http://pro-sftp:8888
    - /etc/initial.json
    command:
    - python3
    image: python:3.9
    imagePullPolicy: IfNotPresent
    name: python
    resources:
      limits:
        cpu: 350m
        memory: 384Mi
      requests:
        cpu: 52m
        memory: 192Mi
    volumeMounts:
    - mountPath: /etc/sftpgo
      name: config
    - mountPath: /etc/initial.json
      name: initial
      subPath: initial.json
  imagePullSecrets:
  - name: fiware-platform-docker-account
  volumes:
  - configMap:
      defaultMode: 420
      name: pro-sftp
    name: config
  - name: initial
    secret:
      defaultMode: 420
      secretName: pro-sftp
