apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wso2si-tooling
    service: {{ .Service | quote }}
    username: {{ .Username | quote }}
  name: "wso2tooling-{{ .Service | replace "_" "-" }}-{{ .Username | replace "_" "-" }}"
  namespace: {{ .Namespace | quote }}
spec:
  containers:
  - image: warpcomdev/wso2si-integrator:1.1.0
    imagePullPolicy: IfNotPresent
    name: wso2tooling
    env:
    - name: HOME
      value: /opt/wso2si
    ports:
    - name: http
      containerPort: 9390
    readinessProbe:
      httpGet:
        path: /editor
        port: 9390
      initialDelaySeconds: 30
      timeoutSeconds: 5
      periodSeconds: 30
      successThreshold: 1
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
    volumeMounts:
    - mountPath: /opt/wso2si
      name: data
      subPath: {{ printf "%s/%s" (.Service | replace "sc_" "") .Username | quote }}
  imagePullSecrets:
  - name: fiware-platform-docker-account
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: "{{ .Namespace | splitList "-" | last }}-sftp-{{ .Service | replace "sc_" "" }}"
