apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wsos2-tooling
    service: {{ .Service | quote }}
    username: {{ .Username | quote }}
  name: "wso2tooling-{{ .Service | replace "_" "-" }}-{{ .Username | replace "_" "-" }}"
  namespace: {{ .Namespace | quote }}
spec:
  containers:
  - image: warpcomdev/wso2si-integrator:1.1.0
    imagePullPolicy: IfNotPresent
    name: wso2tooling
    ports:
    - name: http
      containerPort: 9390
    resources:
      limits:
        cpu: 350m
        memory: 384Mi
      requests:
        cpu: 150m
        memory: 192Mi
    volumeMounts:
    - mountPath: /opt/wso2si
      name: data
      subPath: {{ .Username | quote }}
  imagePullSecrets:
  - name: fiware-platform-docker-account
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: "{{ .Namespace | splitList "-" | last }}-sftp-{{ .Service }}"
